apiVersion: v1
kind: Pod
metadata:
  name: kafka-test-pod
spec:
  containers:
  - name: kafka-test-container
    image: confluentinc/cp-kafka:latest
    command: ["/bin/sh", "-c", "sleep 3600"]
    env:
    - name: KAFKA_BROKER_1
      value: "10.71.71.250:9094"
    - name: KAFKA_BROKER_2
      value: "10.71.71.251:9094"
    - name: KAFKA_BROKER_3
      value: "10.71.71.252:9094"
