ingress:
  main:
    enabled: true
    annotations:
      nginx.ingress.kubernetes.io/rewrite-target: /
    hosts:
      - host: search.alnav.dev
        paths:
          - path: /
            pathType: Prefix
      - host: search.home
        paths:
          - path: /
            pathType: Prefix
    tls: []  # Enable this if you want to add TLS/SSL support
