---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: pool
  namespace: default
spec:
  addresses:
    - 10.71.71.192/26
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: pool
  namespace: default
spec:
  ipAddressPools:
    - pool
