repositories:
  - name: longhorn
    url: https://charts.longhorn.io
  - name: metallb
    url: https://metallb.github.io/metallb
  - name: mojo2600
    url: https://mojo2600.github.io/pihole-kubernetes/
  - name: ingress-nginx
    url: https://kubernetes.github.io/ingress-nginx
  - name: k8s-homelab
    url: https://k8s-home-lab.github.io/helm-charts/
  - name: searxng
    url: https://charts.searxng.org
  - name: damoun
    url: https://charts.damoun.dev
  - name: jaconi
    url: https://charts.jaconi.io
  - name: codecentric
    url: https://codecentric.github.io/helm-charts
  - name: authentik
    url: https://charts.goauthentik.io
  - name: utkuozdemir
    url: https://utkuozdemir.org/helm-charts
  - name: camunda
    url: https://helm.camunda.io
---
releases:
  - name: longhorn
    namespace: longhorn-system
    chart: longhorn/longhorn
    version: 1.6.2
    values:
      - ./values/longhorn.yaml

  - name: metallb
    namespace: metallb-system
    chart: metallb/metallb
    version: 0.14.8

  - name: pihole
    namespace: pihole-system
    chart: mojo2600/pihole
    version: 2.26.1
    values:
      - ./values/pihole.yaml

  - name: ingress-nginx-internal
    namespace: nginx-system
    chart: ingress-nginx/ingress-nginx
    version: 4.10.1
    values:
      - ./values/nginx-internal.yaml

  - name: calibre-web
    namespace: calibre-system
    chart: k8s-home-lab/calibre-web
    version: 9.0.2
    values:
      - ./values/calibre-web.yaml

  # Automatic DNS for pihole
  - name: externaldns-pihole
    namespace: pihole-system
    chart: bitnami/external-dns
    version: 8.0.1
    values:
      - ./values/externaldns.yaml

  - name: searxng
    namespace: searx-system
    chart: searxng/searxng
    version: 1.0.0
    values:
      - ./values/searx.yaml

  - name: torrent
    namespace: torrent-system
    chart: damoun/transmission
    version: 1.7.0
    values:
      - ./values/torrent.yaml
      #- name: kafka
      #  namespace: kafka-system
      #  chart: bitnami/kafka
      #  version: 30.0.4
      #  values:
      #    - ./values/kafka.yaml

  - name: portfolio
    namespace: portfolio-system
    chart: ./charts/portfolio-chart
    values:
      - ./values/portfolio.yaml

  - name: netbird
    namespace: netbird-system
    chart: jaconi/netbird
    version: 0.14.2
    values:
      - ./values/netbird.yaml

  - name: keycloak
    namespace: netbird-system
    chart: codecentric/keycloak
    version: 18.4.4
    values:
      - ./values/keycloak.yaml


  - name: netbird-dashboard
    namespace: netbird-system
    chart: jaconi/netbird-dashboard
    version: 1.0.0
    values:
      - ./values/netbird-dashboard.yaml

  - name: authentik
    namespace: auth-system
    chart: authentik/authentik
    version: 2024.6.3
    values:
      - ./values/authentik.yaml

  - name: jellyfin
    namespace: jellyfin-system
    chart: utkuozdemir/jellyfin
    version: 2.0.0
    values:
      - ./values/jelly.yaml

  - name: camunda
    namespace: camunda-system
    chart: camunda/camunda-platform
    version: 10.3.2
